--
-- PostgreSQL database dump
--

\restrict pV9FEF5j2X9024DpdARK6aoJqIn68TpZRcqdLhhWTdN7eQ0dBARj6TxlclBB5F8

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anotacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.anotacion (
    idanotacion bigint NOT NULL,
    es_publica boolean,
    fecha timestamp(6) without time zone NOT NULL,
    parte character varying(200),
    texto text,
    tiene_spoiler boolean,
    tipo character varying(255) NOT NULL,
    idlibro bigint NOT NULL,
    idusuario bigint NOT NULL,
    CONSTRAINT anotacion_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['NOTA'::character varying, 'CITA'::character varying])::text[])))
);


--
-- Name: anotacion_idanotacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.anotacion ALTER COLUMN idanotacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.anotacion_idanotacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: autor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.autor (
    idautor bigint NOT NULL,
    biografia text,
    foto character varying(500),
    nacionalidad character varying(100),
    nombre character varying(150) NOT NULL,
    seguidores integer
);


--
-- Name: autor_idautor_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.autor ALTER COLUMN idautor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autor_idautor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorito; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorito (
    idusuario bigint NOT NULL,
    idlibro bigint NOT NULL
);


--
-- Name: libro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.libro (
    idlibro bigint NOT NULL,
    anio_publicacion integer,
    genero character varying(100),
    idapiexterna character varying(100),
    isbn character varying(20),
    num_paginas integer,
    portada character varying(500),
    sinopsis text,
    titulo character varying(300) NOT NULL,
    idautor bigint NOT NULL
);


--
-- Name: libro_idlibro_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.libro ALTER COLUMN idlibro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.libro_idlibro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: likea; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.likea (
    idusuario bigint NOT NULL,
    idresena bigint NOT NULL
);


--
-- Name: lista; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lista (
    idlista bigint NOT NULL,
    descripcion text,
    es_automatica boolean,
    es_publica boolean,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    nombre character varying(200) NOT NULL,
    idusuario bigint NOT NULL
);


--
-- Name: lista_idlista_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lista ALTER COLUMN idlista ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lista_idlista_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lista_libro; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lista_libro (
    idlista bigint NOT NULL,
    idlibro bigint NOT NULL
);


--
-- Name: notificacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificacion (
    idnotificacion bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    leida boolean,
    mensaje text,
    tipo character varying(255) NOT NULL,
    idlibro bigint,
    idrecomendacion bigint,
    idresena bigint,
    idusuario bigint NOT NULL,
    idusuario_origen bigint,
    idreto bigint,
    CONSTRAINT notificacion_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['LIKE_RESENA'::character varying, 'NUEVA_RECOMENDACION'::character varying, 'NUEVO_SEGUIDOR'::character varying, 'NUEVA_RESENA_SEGUIDO'::character varying, 'RETO_CUMPLIDO'::character varying, 'NUEVO_LIBRO_AUTOR'::character varying])::text[])))
);


--
-- Name: notificacion_idnotificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notificacion ALTER COLUMN idnotificacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificacion_idnotificacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: participante_reto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.participante_reto (
    idparticipante bigint NOT NULL,
    fecha_cumplimiento timestamp(6) without time zone,
    fecha_union timestamp(6) without time zone NOT NULL,
    progreso integer,
    reto_cumplido boolean,
    id_reto bigint NOT NULL,
    id_usuario bigint NOT NULL
);


--
-- Name: participante_reto_idparticipante_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.participante_reto ALTER COLUMN idparticipante ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participante_reto_idparticipante_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recomendacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recomendacion (
    idrecomendacion bigint NOT NULL,
    es_automatica boolean,
    fecha timestamp(6) without time zone NOT NULL,
    mensaje text,
    visto boolean,
    idusuario_emisor bigint,
    idlibro bigint NOT NULL,
    idusuario_receptor bigint NOT NULL
);


--
-- Name: recomendacion_idrecomendacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recomendacion ALTER COLUMN idrecomendacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recomendacion_idrecomendacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resena; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resena (
    idresena bigint NOT NULL,
    es_publica boolean,
    fecha_creacion timestamp(6) without time zone NOT NULL,
    leidopreviamente boolean,
    puntuacion numeric(2,1),
    texto text,
    tiene_spoiler boolean,
    idlibro bigint NOT NULL,
    idusuario bigint NOT NULL,
    ritmo integer
);


--
-- Name: resena_etiqueta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resena_etiqueta (
    idresena bigint NOT NULL,
    etiqueta character varying(255),
    CONSTRAINT resena_etiqueta_etiqueta_check CHECK (((etiqueta)::text = ANY ((ARRAY['MELANCOLICO'::character varying, 'TRISTE'::character varying, 'ALEGRE'::character varying, 'OSCURO'::character varying, 'ESPERANZADOR'::character varying, 'TENSO'::character varying, 'ROMANTICO'::character varying, 'DIVERTIDO'::character varying, 'REFLEXIVO'::character varying, 'INQUIETANTE'::character varying, 'INSPIRADOR'::character varying, 'NOSTALGICO'::character varying, 'MISTERIOSO'::character varying, 'EPICO'::character varying, 'INTIMO'::character varying, 'PERTURBADOR'::character varying, 'RECONFORTANTE'::character varying, 'AVENTURERO'::character varying, 'POETICO'::character varying, 'PROVOCADOR'::character varying])::text[])))
);


--
-- Name: resena_idresena_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resena ALTER COLUMN idresena ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resena_idresena_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reto (
    idreto bigint NOT NULL,
    fechafin date,
    fechainicio date NOT NULL,
    descripcion character varying(255),
    meta integer NOT NULL,
    modalidad character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL,
    titulo character varying(255) NOT NULL,
    id_autor bigint,
    id_creador bigint,
    CONSTRAINT reto_modalidad_check CHECK (((modalidad)::text = ANY ((ARRAY['PERSONAL'::character varying, 'PREDEFINIDO'::character varying, 'COMPARTIDO'::character varying, 'COLABORATIVO'::character varying])::text[]))),
    CONSTRAINT reto_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PAGINAS'::character varying, 'HORAS'::character varying, 'LIBROS'::character varying, 'LIBROS_AUTOR'::character varying])::text[])))
);


--
-- Name: reto_idreto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reto ALTER COLUMN idreto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reto_idreto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seguimiento; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seguimiento (
    idseguimiento bigint NOT NULL,
    estado character varying(255) NOT NULL,
    fecha date NOT NULL,
    num_pagina integer NOT NULL,
    idlibro bigint NOT NULL,
    idusuario bigint NOT NULL,
    CONSTRAINT seguimiento_estado_check CHECK (((estado)::text = ANY ((ARRAY['LEYENDO'::character varying, 'LEIDO'::character varying, 'ABANDONADO'::character varying])::text[])))
);


--
-- Name: seguimiento_idseguimiento_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seguimiento ALTER COLUMN idseguimiento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seguimiento_idseguimiento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sesion_lectura; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sesion_lectura (
    idsesion bigint NOT NULL,
    duracion_minutos integer,
    fin timestamp(6) without time zone,
    inicio timestamp(6) without time zone NOT NULL,
    id_libro bigint NOT NULL,
    id_usuario bigint NOT NULL
);


--
-- Name: sesion_lectura_idsesion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sesion_lectura ALTER COLUMN idsesion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sesion_lectura_idsesion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sigue; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sigue (
    idusuario_seguidor bigint NOT NULL,
    idusuario_seguido bigint NOT NULL
);


--
-- Name: sigue_autor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sigue_autor (
    idusuario bigint NOT NULL,
    idautor bigint NOT NULL
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuario (
    idusuario bigint NOT NULL,
    avatar character varying(500),
    biografia text,
    email character varying(255) NOT NULL,
    fecha_alta date NOT NULL,
    nombre character varying(150) NOT NULL,
    password character varying(255) NOT NULL,
    seguidores integer,
    rol character varying(255) NOT NULL,
    CONSTRAINT usuario_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);


--
-- Name: usuario_idusuario_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuario ALTER COLUMN idusuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_idusuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anotacion anotacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anotacion
    ADD CONSTRAINT anotacion_pkey PRIMARY KEY (idanotacion);


--
-- Name: autor autor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.autor
    ADD CONSTRAINT autor_pkey PRIMARY KEY (idautor);


--
-- Name: favorito favorito_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT favorito_pkey PRIMARY KEY (idusuario, idlibro);


--
-- Name: libro libro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libro
    ADD CONSTRAINT libro_pkey PRIMARY KEY (idlibro);


--
-- Name: likea likea_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likea
    ADD CONSTRAINT likea_pkey PRIMARY KEY (idusuario, idresena);


--
-- Name: lista_libro lista_libro_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lista_libro
    ADD CONSTRAINT lista_libro_pkey PRIMARY KEY (idlista, idlibro);


--
-- Name: lista lista_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lista
    ADD CONSTRAINT lista_pkey PRIMARY KEY (idlista);


--
-- Name: notificacion notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_pkey PRIMARY KEY (idnotificacion);


--
-- Name: participante_reto participante_reto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participante_reto
    ADD CONSTRAINT participante_reto_pkey PRIMARY KEY (idparticipante);


--
-- Name: recomendacion recomendacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recomendacion
    ADD CONSTRAINT recomendacion_pkey PRIMARY KEY (idrecomendacion);


--
-- Name: resena resena_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resena
    ADD CONSTRAINT resena_pkey PRIMARY KEY (idresena);


--
-- Name: reto reto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reto
    ADD CONSTRAINT reto_pkey PRIMARY KEY (idreto);


--
-- Name: seguimiento seguimiento_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seguimiento
    ADD CONSTRAINT seguimiento_pkey PRIMARY KEY (idseguimiento);


--
-- Name: sesion_lectura sesion_lectura_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion_lectura
    ADD CONSTRAINT sesion_lectura_pkey PRIMARY KEY (idsesion);


--
-- Name: sigue_autor sigue_autor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sigue_autor
    ADD CONSTRAINT sigue_autor_pkey PRIMARY KEY (idusuario, idautor);


--
-- Name: sigue sigue_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sigue
    ADD CONSTRAINT sigue_pkey PRIMARY KEY (idusuario_seguidor, idusuario_seguido);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: participante_reto ukp245vbbb0edgu9b0lqkwwutc0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participante_reto
    ADD CONSTRAINT ukp245vbbb0edgu9b0lqkwwutc0 UNIQUE (id_reto, id_usuario);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (idusuario);


--
-- Name: reto fk1gvs9ho420n3v14vgmkrp5qvx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reto
    ADD CONSTRAINT fk1gvs9ho420n3v14vgmkrp5qvx FOREIGN KEY (id_creador) REFERENCES public.usuario(idusuario);


--
-- Name: anotacion fk1xpp1s0v0p79ob1urxl1ww34h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anotacion
    ADD CONSTRAINT fk1xpp1s0v0p79ob1urxl1ww34h FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: sesion_lectura fk263ec846aylbh07x230hvpf08; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion_lectura
    ADD CONSTRAINT fk263ec846aylbh07x230hvpf08 FOREIGN KEY (id_usuario) REFERENCES public.usuario(idusuario);


--
-- Name: lista_libro fk2s38aymrvbu56wm9ddkj1pr67; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lista_libro
    ADD CONSTRAINT fk2s38aymrvbu56wm9ddkj1pr67 FOREIGN KEY (idlista) REFERENCES public.lista(idlista);


--
-- Name: notificacion fk3i3dg2pv0uygiyl53fbcf97ae; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fk3i3dg2pv0uygiyl53fbcf97ae FOREIGN KEY (idusuario_origen) REFERENCES public.usuario(idusuario);


--
-- Name: recomendacion fk4sd32r746taglo7dgohos3obg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recomendacion
    ADD CONSTRAINT fk4sd32r746taglo7dgohos3obg FOREIGN KEY (idusuario_emisor) REFERENCES public.usuario(idusuario);


--
-- Name: seguimiento fk678tjq6ij2i0c48ii5i8pjy20; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seguimiento
    ADD CONSTRAINT fk678tjq6ij2i0c48ii5i8pjy20 FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: recomendacion fk69bdseno27yrfgd80i2ckxmo3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recomendacion
    ADD CONSTRAINT fk69bdseno27yrfgd80i2ckxmo3 FOREIGN KEY (idusuario_receptor) REFERENCES public.usuario(idusuario);


--
-- Name: seguimiento fk6av1ltacjqwkpnrkp053pxox7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seguimiento
    ADD CONSTRAINT fk6av1ltacjqwkpnrkp053pxox7 FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: favorito fk6jckox7d8cb3udax06q73m3o6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT fk6jckox7d8cb3udax06q73m3o6 FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: notificacion fk8x8gihsj9h3pik41a3j2artg9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fk8x8gihsj9h3pik41a3j2artg9 FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: resena fka6jf9s9y354h9fj2s57p50cs2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resena
    ADD CONSTRAINT fka6jf9s9y354h9fj2s57p50cs2 FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: participante_reto fkauy4827b4ilhl97v920kt3fp6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participante_reto
    ADD CONSTRAINT fkauy4827b4ilhl97v920kt3fp6 FOREIGN KEY (id_usuario) REFERENCES public.usuario(idusuario);


--
-- Name: sigue_autor fkb30d1gu1jpws5dp6txcdv7r97; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sigue_autor
    ADD CONSTRAINT fkb30d1gu1jpws5dp6txcdv7r97 FOREIGN KEY (idautor) REFERENCES public.autor(idautor);


--
-- Name: recomendacion fkbmalmolovedon0peeuu2ntd1j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recomendacion
    ADD CONSTRAINT fkbmalmolovedon0peeuu2ntd1j FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: reto fkd0cr2lllx170a4k4nykqqnq8n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reto
    ADD CONSTRAINT fkd0cr2lllx170a4k4nykqqnq8n FOREIGN KEY (id_autor) REFERENCES public.autor(idautor);


--
-- Name: libro fkdigypv1t1jn2rdmgtfvos92i3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.libro
    ADD CONSTRAINT fkdigypv1t1jn2rdmgtfvos92i3 FOREIGN KEY (idautor) REFERENCES public.autor(idautor);


--
-- Name: likea fkhpxqlfc4ytu9sltr3qjynlbiu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likea
    ADD CONSTRAINT fkhpxqlfc4ytu9sltr3qjynlbiu FOREIGN KEY (idresena) REFERENCES public.resena(idresena);


--
-- Name: notificacion fkhr8onute56m34qesw1wtoqmpj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fkhr8onute56m34qesw1wtoqmpj FOREIGN KEY (idreto) REFERENCES public.reto(idreto);


--
-- Name: sigue fkii4qt9khs9ibt3vgk3k0rnduf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sigue
    ADD CONSTRAINT fkii4qt9khs9ibt3vgk3k0rnduf FOREIGN KEY (idusuario_seguido) REFERENCES public.usuario(idusuario);


--
-- Name: favorito fkiqg2216cxg83ov01h499aqaaa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorito
    ADD CONSTRAINT fkiqg2216cxg83ov01h499aqaaa FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: sigue fkjsq13sycjx4qhqpyfr7k1ul63; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sigue
    ADD CONSTRAINT fkjsq13sycjx4qhqpyfr7k1ul63 FOREIGN KEY (idusuario_seguidor) REFERENCES public.usuario(idusuario);


--
-- Name: participante_reto fkk4ei7y8iwuu57w2gjwaswmdq5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participante_reto
    ADD CONSTRAINT fkk4ei7y8iwuu57w2gjwaswmdq5 FOREIGN KEY (id_reto) REFERENCES public.reto(idreto);


--
-- Name: lista fkl6n6w7oeyr1hipfld8sd1hesi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lista
    ADD CONSTRAINT fkl6n6w7oeyr1hipfld8sd1hesi FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: sigue_autor fklwp52ikiuhrkmja5xcx8odefq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sigue_autor
    ADD CONSTRAINT fklwp52ikiuhrkmja5xcx8odefq FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: anotacion fkngixn5vflpvbmwmnavr1bfog4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.anotacion
    ADD CONSTRAINT fkngixn5vflpvbmwmnavr1bfog4 FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: resena fknrcly3akdei5wibfuqv3hrdac; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resena
    ADD CONSTRAINT fknrcly3akdei5wibfuqv3hrdac FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: lista_libro fkq27necg7lh86kmh02uvg6xkws; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lista_libro
    ADD CONSTRAINT fkq27necg7lh86kmh02uvg6xkws FOREIGN KEY (idlibro) REFERENCES public.libro(idlibro);


--
-- Name: resena_etiqueta fkq2lp7gjelxf53e2eqok17ata4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resena_etiqueta
    ADD CONSTRAINT fkq2lp7gjelxf53e2eqok17ata4 FOREIGN KEY (idresena) REFERENCES public.resena(idresena);


--
-- Name: sesion_lectura fkqeggemkq16rbxrdi5igdnl2cl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sesion_lectura
    ADD CONSTRAINT fkqeggemkq16rbxrdi5igdnl2cl FOREIGN KEY (id_libro) REFERENCES public.libro(idlibro);


--
-- Name: likea fkqssc52b32vveoy1md130bu6yo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.likea
    ADD CONSTRAINT fkqssc52b32vveoy1md130bu6yo FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: notificacion fkquhorqr77bk5svyml6q28vu9l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fkquhorqr77bk5svyml6q28vu9l FOREIGN KEY (idusuario) REFERENCES public.usuario(idusuario);


--
-- Name: notificacion fkt6baym89naw0vvlhw23042u2b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fkt6baym89naw0vvlhw23042u2b FOREIGN KEY (idrecomendacion) REFERENCES public.recomendacion(idrecomendacion);


--
-- Name: notificacion fkw8g6h82f5d9sp89gwf4c7h61; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT fkw8g6h82f5d9sp89gwf4c7h61 FOREIGN KEY (idresena) REFERENCES public.resena(idresena);


--
-- PostgreSQL database dump complete
--

\unrestrict pV9FEF5j2X9024DpdARK6aoJqIn68TpZRcqdLhhWTdN7eQ0dBARj6TxlclBB5F8

